# ASP.NET Core (.NET 7)
# Build and test .NET 7 projects
# Add steps for publishing/deployment if needed

trigger:
- main   # altera se sua branch principal for "master"

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Instala SDK do .NET 7
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'

# Restaura pacotes
- script: dotnet restore
  displayName: 'Restore dependencies'

# Compila a solução em Release
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build solution'

# Roda testes unitários (se houver projeto de testes)
- script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run unit tests'

# Publica artefato (gera pasta "publish" para deploy)
- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish project'

# Salva artefato gerado (pode ser usado em deploy posterior)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
