# azure-pipelines.yml
# CI for ASP.NET Core (.NET 8)
# Runs on push/merge to master and on Pull Requests targeting master

trigger:
- master  # runs after merge/push to master

pr:
- master  # runs on PRs targeting master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  artifactName: 'drop'

steps:
# 1) Checkout repository (clean)
- checkout: self
  clean: true

# 2) Install .NET 8 SDK
- task: UseDotNet@2
  displayName: 'Use .NET SDK 8'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# 3) Restore dependencies using the installed SDK
- script: dotnet restore
  displayName: 'Restore dependencies'
  env:
    DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet

# 4) Build solution
- script: dotnet build --configuration $(buildConfiguration) --no-restore --verbosity minimal
  displayName: 'Build solution'
  env:
    DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet

# 5) Run unit tests
- script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run unit tests'
  env:
    DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet

# 6) Publish project (creates output ready for deployment)
- script: dotnet publish --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Publish project'
  env:
    DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet

# 7) Publish build artifacts for deployment
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: '$(artifactName)'
    publishLocation: 'Container'
